### ISSUE TITLE
Support for UnicodeSetAttribute

### ISSUE THREAD

**Issue by mexekanez** [mathewmarcus/marshmallow-pynamodb#1]
could you please add support for this field type

**Comment by mathewmarcus** [comment]
Yes, this will be included as part of the next release along with support for `NumberSetAttribute`

**Comment by mexekanez** [comment]
in general I solved it with MapAttribute

**Comment by mathewmarcus** [comment]
Support for `NumberSetAttribute`s and `UnicodeSetAttribute`s has been added
